cmake_minimum_required(VERSION 3.12)
project(WeightedStraightSkeleton)

set(CMAKE_CXX_STANDARD 20)
set(VCPKG_TARGET_TRIPLET "wasm32-emscripten")

# Disable GMP/MPFR and force Boost.Multiprecision as CGAL’s backend
set(CGAL_DISABLE_GMP ON)
set(CGAL_CMAKE_EXACT_NT_BACKEND BOOST_BACKEND)

find_package(CGAL REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE CGAL::CGAL)

if (EMSCRIPTEN)
    set(CMAKE_EXECUTABLE_SUFFIX ".js")

    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -O3")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ALLOW_MEMORY_GROWTH=1")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ASSERTIONS=1")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s NO_DISABLE_EXCEPTION_CATCHING")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} --no-entry")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s SINGLE_FILE")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ENVIRONMENT='web'")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s MODULARIZE=1")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORT_ES6=1")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s NO_EXIT_RUNTIME=1")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORTED_FUNCTIONS=['_malloc','_free']")
    set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORTED_RUNTIME_METHODS=['HEAPU8','HEAPU32','HEAPF32']")

    set_target_properties(main PROPERTIES LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS}")
endif ()
